---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 为提高安全性，请配置 NetApp Backup and Recovery 中特定角色的访问权限。 
---
= 在 NetApp Backup and Recovery 中设置基于角色的访问控制
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在 NetApp Console 中配置基于角色的访问控制 (RBAC)，以控制谁可以访问 NetApp Backup and Recovery 资源。您可以将管理员或查看器角色分配给支持 RBAC 的工作负载。在项目级别或机群级别关联可用之前，尚未支持 RBAC 的工作负载仍可供所有具有 Backup and Recovery 角色的用户访问。


NOTE: NetApp Console 使用项目来组织文件夹中的资源，而 NetApp Console 本地部署将项目称为舰队。

要控制对组织中资源的访问，请在 NetApp Console 的*管理 > 身份和访问*页面中完成这些步骤。


NOTE: 这些步骤假设您在 NetApp Console 中被分配了组织管理员角色。

.步骤
. 创建身份和访问项目结构。
+
作为组织管理员，设置工作负载所在的文件夹和项目结构。

. 分配用户角色。
+
.. 主要选项：
+
将用户添加到指定用于工作负载的每个项目，并授予他们适当的角色。例如：

+
*** *Organization admin* 和 *Backup and Recovery super admin*：具有这些角色的用户可以查看组织中的所有资源，并可以发现 Backup and Recovery 工作负载并将其分配给项目（例如，美国东部或美国西部）。
*** *文件夹或项目管理员*和 *Backup and Recovery super admin*：具有这些角色的用户只能查看其分配的文件夹或项目中的资源，但可以发现 Backup and Recovery 工作负载并将其分配给该项目。


.. 备选方案：
+
您可以为自己分配 Backup and Recovery 超级管理员角色并直接发现工作负载，而不是授予用户完整的 Backup and Recovery 管理员访问权限。



. 在 Backup and Recovery 中发现工作负载。
+
组织管理员或文件夹或项目管理员发现可用的工作负载，并选择适当的项目（例如美国东部或美国西部）。每个工作负载都会自动与选定项目关联。

. 将用户添加到项目。
+
组织管理员或文件夹或项目管理员将 NetApp Console 用户添加到具有工作负载的项目。根据用户的访问需求，为其分配组织查看者角色和 Backup and Recovery 角色。具有适当 Backup and Recovery 角色的用户会自动获得对这些项目中新工作负载的访问权限。





[[related-information]]
== 相关信息

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["了解 NetApp Console 身份和访问管理"^]。
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console中的NetApp Backup and Recovery角色"^]。

