---
sidebar: sidebar 
permalink: br-reference-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 已知限制标识了该产品的此版本不支持的功能，或者不能与其正确互操作的功能。仔细审查这些限制。 
---
= NetApp Backup and Recovery for ONTAP卷的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制标识了此版本的NetApp Backup and Recovery 不支持的功能，或者不能与其正确互操作的功能。仔细审查这些限制。

* NetApp Backup and Recovery 可以将Cloud Volumes ONTAP备份到 AWS 中国区域（包括北京和宁夏）的对象存储；但是，您可能需要先手动修改身份和访问策略。
+
有关在 AWS 中创建控制台代理的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-bluexp.html["在 AWS 中安装控制台代理"^]。

+
有关更多详细信息，请参阅博客文章 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["NetApp备份和恢复功能博客 2023 年 5 月"^]。

* NetApp Backup and Recovery 不支持 Microsoft Azure 中国区域。
+
有关在 Azure 中创建控制台代理的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-azure-bluexp.html["在 Azure 中安装控制台代理"^]。

* NetApp Backup and Recovery 不支持FlexCache卷的备份。




== ONTAP卷的复制限制

* 您一次只能选择一个FlexGroup卷进行复制。您需要为每个FlexGroup卷单独激活备份。
+
FlexVol卷没有限制 - 您可以选择系统中的所有FlexVol卷并分配相同的备份策略。

* 支持以下功能 https://docs.netapp.com/us-en/data-services-replication/index.html["NetApp复制"]，但在使用NetApp Backup and Recovery 的复制功能时则不然：
+
** 不支持从卷 A 到卷 B 以及从卷 B 到卷 C 的级联配置复制。支持从卷 A 到卷 B 的复制。
** 不支持在 FSx for ONTAP系统之间复制数据。
** 不支持创建卷的一次性复制。


* 从本地ONTAP系统创建复制时，如果目标Cloud Volumes ONTAP系统上的ONTAP版本为 9.8、9.9 或 9.11，则只允许镜像保管库策略。




== ONTAP卷的备份到对象限制

* 备份数据时， NetApp Backup and Recovery 将不会维护NetApp卷加密 (NVE)。这意味着 NVE 卷上的加密数据将在数据传输到目标时被解密，并且加密将无法维持。
+
有关这些加密类型的说明，请参阅https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["配置NetApp卷加密概述"^]。



* 如果使用SnapMirror策略中的计划在SnapMirror目标卷上启用长期保留快照，则会直接在目标卷上创建快照。在这种情况下，您不应使用NetApp Backup and Recovery 备份这些卷，因为这些快照不会移动到对象存储。
* 备份数据时， NetApp Backup and Recovery 将不会维护NetApp卷加密 (NVE)。这意味着 NVE 卷上的加密数据将在数据传输到目标时被解密，并且加密将无法维持。
+
有关这些加密类型的说明，请参阅https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["配置NetApp卷加密概述"^]。



* 如果使用SnapMirror策略中的计划在SnapMirror目标卷上启用长期保留快照，则会直接在目标卷上创建快照。在这种情况下，您不应使用NetApp Backup and Recovery 备份这些卷，因为这些快照不会移动到对象存储。
* 当您创建或编辑备份策略但未向该策略分配任何卷时，保留的备份数量最多可以为 1018。将卷分配给策略后，您可以编辑该策略以创建最多 4000 个备份。
* 备份数据保护 (DP) 卷时：
+
** 与SnapMirror标签的关系 `app_consistent`和 `all_source_snapshot`不会备份到云端。
** 如果您在SnapMirror目标卷上创建快照的本地副本（无论使用何种SnapMirror标签），这些快照都不会作为备份移动到云端。此时，您需要为源 DP 卷创建一个带有所需标签的 Snapshot 策略，以便NetApp Backup and Recovery 对其进行备份。


* FlexGroup卷备份无法移动到档案存储。
* 如果集群运行的是ONTAP 9.13.1 或更高版本， FlexGroup卷备份可以使用 DataLock 和勒索软件保护。
* SVM-DR 卷备份受以下限制支持：
+
** 仅支持从ONTAP辅助节点进行备份。
** 应用于卷的快照策略必须是NetApp Backup and Recovery 可识别的策略之一，包括每日、每周、每月等。默认的“sm_created”策略（用于*镜像所有快照*）无法识别，并且 DP 卷不会显示在可备份的卷列表中。
** 当从源或目标进行备份时，SVM-DR 和卷备份和恢复完全独立工作。唯一的限制是 SVM-DR 不会复制SnapMirror云关系。在 DR 场景中，当 SVM 在辅助位置上线时，您必须手动更新SnapMirror云关系。




* MetroCluster支持：
+
** 当您使用ONTAP 9.12.1 GA 或更高版本时，连接到主系统时支持备份。整个备份配置被传输到辅助系统，以便切换后自动继续备份到云端。您不需要在辅助系统上设置备份（事实上，您被禁止这样做）。
** 当您使用ONTAP 9.12.0 及更早版本时，仅支持从ONTAP辅助系统进行备份。
** 目前不支持FlexGroup卷的备份。


* 数据保护卷不支持使用“*立即备份*”按钮进行临时卷备份。
* 不支持 SM-BC 配置。
* ONTAP不支持从单个卷到多个对象存储的SnapMirror关系扇出；因此， NetApp Backup and Recovery 不支持此配置。
* 目前，Amazon S3、Azure 和StorageGRID支持对象存储上的 WORM/Compliance 模式。这被称为 DataLock 功能，必须使用NetApp备份和恢复设置来管理，而不是使用云提供商界面。




== ONTAP卷的还原限制

这些限制适用于恢复文件和文件夹的搜索和恢复方法以及浏览和恢复方法；除非特别指出。

* 浏览和恢复一次最多可以恢复 100 个单独的文件。
* 搜索和恢复一次可以恢复 1 个文件。
* 使用ONTAP 9.13.0 或更高版本时，“浏览和还原”和“搜索和还原”可以还原文件夹及其内的所有文件和子文件夹。
+
使用高于 9.11.1 但低于 9.13.0 的ONTAP版本时，还原操作只能还原选定的文件夹及其中的文件，而不会还原子文件夹或子文件夹中的文件。

+
使用 9.11.1 之前的ONTAP版本时，不支持文件夹还原。

* 仅当集群运行ONTAP 9.13.1 及更高版本时，才支持对驻留在档案存储中的数据进行目录/文件夹还原。
* 仅当集群运行ONTAP 9.13.1 及更高版本时，才支持使用 DataLock 保护的数据的目录/文件夹还原。
* 目前不支持通过复制和/或本地快照进行目录/文件夹还原。
* 不支持从FlexGroup卷还原到FlexVol卷，或从FlexVol卷还原到FlexGroup卷。
* 正在恢复的文件必须使用与目标卷上的语言相同的语言。如果语言不一样，您将收到一条错误消息。
* 将数据从 Azure 档案存储还原到StorageGRID系统时，不支持“高”还原优先级。
* 如果您备份了 DP 卷，然后决定中断与该卷的SnapMirror关系，则无法将文件还原到该卷，除非您也删除SnapMirror关系或反转SnapMirror方向。
* 快速恢复限制：
+
** 目标位置必须是使用ONTAP 9.13.0 或更高版本的Cloud Volumes ONTAP系统。
** 它不支持位于存档存储中的备份。
** 仅当创建云备份的源系统运行ONTAP 9.12.1 或更高版本时，才支持FlexGroup卷。
** 仅当创建云备份的源系统运行ONTAP 9.11.0 或更高版本时，才支持SnapLock卷。



