---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery需要首先发现工作负载，以便您保护它们。 
---
= 在 NetApp Backup and Recovery 中发现 Oracle 数据库工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
发现 Oracle 数据库使 NetApp Backup and Recovery 能够通过创建和恢复备份和快照来保护它们。

*所需的控制台角色* 备份和恢复超级管理员。了解详情link:reference-roles.html["备份和恢复角色和权限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp Console访问角色"^] 。



== 添加 Oracle 数据库主机并发现资源

添加 Oracle 主机信息并让NetApp Backup and Recovery发现工作负载。在每个控制台代理中，选择您想要发现工作负载的系统。

.步骤
. 从NetApp Console菜单中，选择“保护”>“备份和恢复”。
. 在“工作负载”下，选择“Oracle”磁贴。
. 选择*发现资源*。
. 为 *Workload type* 字段选择 *Oracle*。
. 如果您尚未为此 Oracle 数据库主机存储凭据，请选择 *添加凭据*。
+
.. 选择与该主机一起使用的控制台代理。
.. 输入此凭证的名称。
.. 输入该帐户的用户名和密码。
.. 选择*完成*。


. *主机注册*：添加新的 Oracle 数据库主机。在 *主机 FQDN 或 IP 地址* 字段中，输入主机的 FQDN 或 IP 地址 - 对于集群数据库，您可以输入集群中任何节点的 FQDN 或 IP。然后提供凭据、Console 代理和端口号。
. （可选）如果为非 root 用户选择凭据，请执行以下操作：
+
.. 有关如何将您选择的非根用户添加到 Oracle 数据库主机上的 sudoers 文件的说明，请选择*配置 sudoers*。
.. 按照对话框中的说明进行操作，完成后启用复选框，然后选择 *Done*。


. *高级设置*：执行以下操作：
+
.. 输入要用于 NetApp 插件的端口和安装路径。该插件支持 Oracle 数据库主机与 NetApp Backup and Recovery 之间的通信。
.. 选择是允许 NetApp Backup and Recovery 在每台主机上自动安装插件，还是跳过所有主机的自动插件安装。选择 *Show me how* 进行手动安装说明。
+
[NOTE]
====
Backup and Recovery 通过 SSH 连接到每个主机以自动安装插件。当以下任一情况适用时，启用*使用手动安装*：

*** 一个或多个主机未运行 SSH 服务。
*** 任何主机都已具有 NetApp 插件（包括仅部分群集成员具有该插件）。
*** 您希望在每台主机上手动安装此插件。


====
.. 如果数据库主机是集群的，请启用 *添加集群中的所有主机* 选项以发现集群中的所有主机。
.. 选择是否在每台主机上运行安装前检查，然后再自动安装插件。如果检查失败，自动插件安装将停止。要绕过检查并进行安装，请启用 *跳过可选的预安装检查*（如果您选择手动安装，则会自动启用）。


. 选择*发现*。
+

TIP: 添加资源可能需要几分钟的时间。要查看进度，请在 Inventory 页面底部的状态对话框中选择 *Track progress*，或从左侧菜单中选择 *Monitoring*。



.结果
Oracle 数据库工作负载显示在"清单"页面上的工作负载列表中。



== 继续访问NetApp Backup and Recovery仪表板

. 从NetApp Console菜单中，选择 *保护* > *备份和恢复*。
. 选择一个工作负载图块（例如，Microsoft SQL Server）。
. 从备份和恢复菜单中，选择*仪表板*。
. 审查数据保护的健康状况。处于危险中或受保护的工作负载的数量会根据新发现、受保护和备份的工作负载而增加。

