---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery 需要首先发现工作负载，以便您使用该服务。 
---
= 探索NetApp备份和恢复中的 Kubernetes 工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery需要在保护 Kubernetes 工作负载之前发现它们。

*所需的NetApp控制台角色* 备份和恢复超级管理员。了解link:reference-roles.html["备份和恢复角色和权限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp控制台访问角色"^] 。



== 发现 Kubernetes 工作负载

在备份和恢复清单中，发现您环境中的 Kubernetes 工作负载。添加工作负载会将 Kubernetes 集群添加到NetApp Backup and Recovery。然后，您可以添加应用程序并保护集群资源。

.步骤
. 执行以下操作之一：
+
** 如果您是第一次发现 Kubernetes 工作负载，请在NetApp Backup and Recovery 中选择 Kubernetes 工作负载类型下的 *Discover and Manage*。
** 如果您已经发现 Kubernetes 工作负载，请在NetApp Backup and Recovery 中选择 *Inventory* > *Workloads*，然后选择 *Discover resources*。


. 选择 *Kubernetes* 工作负载类型。
. 输入集群名称并选择与集群一起使用的连接器。
. 按照出现的命令行说明进行操作：
+
** 创建Trident保护命名空间
** 创建 Kubernetes 机密
** 添加 Helm 存储库
** 安装Trident Protect 和Trident Protect 连接器
+
这些步骤确保NetApp Backup and Recovery 可以与集群交互。



. 完成这些步骤后，选择*发现*。
+
该集群已添加到清单中。

. 在关联的 Kubernetes 工作负载中选择“查看”以查看该工作负载的应用程序、集群和命名空间列表。




== 继续访问NetApp备份和恢复仪表板

按照以下步骤查看NetApp Backup and Recovery仪表板。

. 从顶部菜单中选择*仪表板*。
. 审查数据保护的健康状况。处于危险中或受保护的工作负载的数量会根据新发现、受保护和备份的工作负载而增加。
+
link:br-use-dashboard.html["了解仪表板显示的内容"] 。


