---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery需要首先发现工作负载，以便您使用该服务。 
---
= 探索NetApp Backup and Recovery中的 Kubernetes 工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery需要在保护 Kubernetes 工作负载之前发现它们。

*所需的NetApp Console角色* 备份和恢复超级管理员。了解详情link:reference-roles.html["备份和恢复角色和权限"]。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp Console访问角色"^] 。



== 发现 Kubernetes 工作负载

在备份和恢复清单中，发现您环境中的 Kubernetes 工作负载。添加工作负载会将 Kubernetes 集群添加到NetApp Backup and Recovery。然后，您可以添加应用程序并保护集群资源。

[NOTE]
====
当您发现当前受 Trident Protect 保护的群集时，在发现过程中将禁用与 Trident Protect 一起使用的任何备份计划（Trident Protect 备份计划与 Backup and Recovery 不兼容）。要保护群集的应用程序，link:br-use-policies-create.html["创建新的保护策略"]或将应用程序与现有策略关联。然后，如果需要，您可以删除 Trident Protect 备份计划。

====
.步骤
. 执行以下操作之一：
+
** 如果您是第一次发现 Kubernetes 工作负载，请在NetApp Backup and Recovery中，在“工作负载”下，选择“Kubernetes”磁贴。
** 如果您已经发现 Kubernetes 工作负载，请在NetApp Backup and Recovery中选择 *Inventory* > *Workloads*，然后选择 *Discover resources*。


. 选择 *Kubernetes* 工作负载类型。
. 输入集群名称并选择与集群一起使用的连接器。
. 按照出现的命令行说明进行操作：
+
** 创建 Trident Protect 命名空间
** 创建 Kubernetes 机密
** 添加 Helm 存储库
** 安装或升级 Trident Protect 和 Trident Protect 连接器
+
这些步骤确保NetApp Backup and Recovery可以与集群交互。



. 完成这些步骤后，选择*发现*。
+
该集群已添加到清单中。

. 在关联的 Kubernetes 工作负载中选择“查看”以查看该工作负载的应用程序、集群和命名空间列表。




== 继续访问NetApp Backup and Recovery仪表板

按照以下步骤查看NetApp Backup and Recovery仪表板。

. 从NetApp Console菜单中，选择 *保护* > *备份和恢复*。
. 选择一个工作负载图块（例如，Microsoft SQL Server）。
. 从备份和恢复菜单中，选择*仪表板*。
. 审查数据保护的健康状况。处于危险中或受保护的工作负载的数量会根据新发现、受保护和备份的工作负载而增加。
+
link:br-use-dashboard.html["了解仪表板显示的内容"]。


