---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery需要首先发现工作负载，以便您使用该服务。 
---
= 探索NetApp Backup and Recovery中的 Kubernetes 工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 NetApp Backup and Recovery 中发现 Kubernetes 集群及其工作负载，以便您可以通过保护策略对其进行保护。

*必需的 NetApp Console 角色*备份和恢复超级管理员。如果要保护存储在 Cloud Volumes ONTAP 集群上的数据，则还需要 Cloud Volumes ONTAP 管理员角色。了解link:reference-roles.html["备份和恢复角色和权限"]…… https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp Console访问角色"^]。



[[discover-kubernetes-workloads]]
== 发现 Kubernetes 工作负载

在备份和恢复清单中，发现环境中的 Kubernetes 集群和工作负载。添加集群使您能够在 NetApp Backup and Recovery 中注册集群，并发现其应用程序和资源以进行保护。您可以选择使用 NetApp Console 本地部署来发现气隙本地 Kubernetes 资源。

[NOTE]
====
当您发现当前受 Trident Protect 保护的集群时，在发现过程中将禁用与 Trident Protect 一起使用的任何备份计划，因为 Trident Protect 备份计划与备份和恢复不兼容。要保护集群的应用程序，link:br-use-policies-create.html["创建新的保护策略"]或将应用程序与现有策略关联。如果需要，您可以随后删除 Trident Protect 备份计划。

====
.步骤
. 执行以下操作之一：
+
** 如果您是第一次发现 Kubernetes 工作负载，请在NetApp Backup and Recovery中，在“工作负载”下，选择“Kubernetes”磁贴。
** 如果您已经发现 Kubernetes 工作负载，请在NetApp Backup and Recovery中选择 *Inventory* > *Workloads*，然后选择 *Discover resources*。


. 选择 *Kubernetes* 工作负载类型。
. 输入集群名称并选择要与集群一起使用的控制台代理。
+
备份和恢复提供根据所选安装类型而变化的说明。如果使用 NetApp Console 本地部署，则可以选择相应说明来发现没有外部网络连接的气隙资源。

. 请选择一种安装类型，以查看在 Kubernetes 集群上安装 Trident Protect 的说明：
+
** 选择*已连接*以发现具有外部网络连接的集群。
** 选择 *Air-gapped* 以发现没有外部网络连接的集群。
+
[role="tabbed-block"]
====
.已连接发现
--
... 按照 Backup and Recovery 中显示的命令行说明进行操作。这些步骤可确保 Backup and Recovery 能够与集群进行交互。


--
.气隙发现
--
... 输入您的私有 Docker 容器注册表的 URL。此注册表用于在安装过程中下载 Trident Protect 和 Trident Protect Connector 映像。
... 如果专用容器注册表需要身份验证，请使用以下方法之一配置注册表凭据：
+
**** *节点级身份验证*：在每个节点的容器运行时中配置注册表凭据。配置完成后，所有 Pod 都可以拉取镜像，而无需额外的 Helm 设置。
**** *Kubernetes image pull secret*：在 `trident-protect`命名空间中创建 Kubernetes image pull secret，然后在 Trident Protect 安装说明中的 Helm 升级步骤中引用它：
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... 按照 Backup and Recovery 中显示的命令行说明，在 Helm 步骤中添加映像拉取密钥信息（如果需要）。这些步骤确保 Backup and Recovery 可以与集群交互。


--
====


. 完成 Trident Protect 安装步骤后，选择 *Discover*。
+
该集群已添加到清单中。

. 在关联的 Kubernetes 工作负载中选择“查看”以查看该工作负载的应用程序、集群和命名空间列表。




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== 继续访问NetApp Backup and Recovery仪表板

按照以下步骤查看 NetApp Backup and Recovery 仪表板并验证已发现的资源。

. 从NetApp Console菜单中，选择 *保护* > *备份和恢复*。
. 选择 Kubernetes workload tile。
. 从备份和恢复菜单中，选择*仪表板*。
. 审查数据保护的健康状况。处于危险中或受保护的工作负载的数量会根据新发现、受保护和备份的工作负载而增加。
+
link:br-use-dashboard.html["了解仪表板显示的内容"]。


