---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery 使您能够取消保护并删除 Kubernetes 应用程序及相关资源。 
---
= 管理 Kubernetes 应用程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 使您能够取消保护并删除 Kubernetes 应用程序及相关资源。

.所需的NetApp控制台角色
组织管理员或SnapCenter管理员。link:reference-roles.html["了解NetApp备份和恢复访问角色"] 。 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp控制台访问角色"^] 。



== 取消保护 Kubernetes 应用程序

如果您不再需要保护某个应用程序，可以取消保护。当您取消保护应用程序时， NetApp Backup and Recovery 会停止保护该应用程序，但保留所有相关的备份和快照。

.步骤
. 在NetApp Backup and Recovery 中，选择 *Inventory*。
. 选择一个 Kubernetes 实例，然后选择“查看”以查看与该实例关联的资源。
. 选择“*应用程序*”选项卡。
. 在应用程序列表中，选择要取消保护的应用程序并选择相关的操作菜单。
. 选择*取消保护*。
. 阅读通知，准备好后，选择*取消保护*。




== 删除 Kubernetes 应用程序

如果您不再需要某个应用程序，可以将其删除。当您删除应用程序时， NetApp Backup and Recovery 将停止保护该应用程序并删除所有相关的备份和快照。

.步骤
. 在NetApp Backup and Recovery 中，选择 *Inventory*。
. 选择一个 Kubernetes 实例，然后选择“查看”以查看与该实例关联的资源。
. 选择“*应用程序*”选项卡。
. 在应用程序列表中，选择要删除的应用程序并选择相关的操作菜单。
. 选择*删除*。
. 启用*删除快照和备份*以删除应用程序的所有快照和备份。
+

CAUTION: 您将无法再使用这些快照和备份恢复应用程序。

. 确认操作并选择*删除*。

