---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用 NetApp Backup and Recovery 保护您的 Oracle Database 工作负载。 
---
= 使用 NetApp Backup and Recovery 还原 Oracle 数据库工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 NetApp Backup and Recovery 从快照、辅助存储上的复制备份或对象存储中存储的备份还原 Oracle 数据库工作负载。

.从这些位置恢复
您可以从不同的起始位置恢复数据库：

* 从主位置恢复（本地快照）
* 从二级存储上的复制资源恢复
* 从对象存储备份恢复


.恢复到这些点
您可以将数据恢复到原始位置；在此私人预览版中不提供恢复到备用位置的功能。

* 恢复到原始位置




[[how-oracle-database-restore-works]]
== Oracle 数据库还原的工作原理

还原 Oracle 数据库工作负载时，将发生以下情况：

* 当您从本地快照恢复数据库时， NetApp Backup and Recovery会使用备份中的数据创建一个_新_资源。
* 从复制的存储恢复时，您可以将其恢复到原始位置。
* 从对象存储还原备份时，您可以将数据还原到源存储或本地ONTAP系统，然后从那里恢复数据库。


从“恢复”页面（也称为“搜索和恢复”），您可以恢复数据库，即使您不记得确切的名称、它所在的位置或它最后处于良好状态的日期。您可以使用过滤器搜索数据库。



[[restore-an-oracle-database]]
== 还原 Oracle 数据库

根据您的需要，将 Oracle 数据库还原到特定时间点、特定系统更改编号 (SCN) 或最后一个正常状态。您也可以从快照还原数据库并跳过自动恢复过程，例如，如果您希望手动执行恢复。您可以使用数据库名称或特定筛选器搜索数据库。

*必需的 NetApp Console 角色* 备份和恢复超级管理员或备份和恢复还原管理员角色 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服务的NetApp Console访问角色"^]。

.步骤
. 从NetApp Console菜单中，选择“保护”>“备份和恢复”。
. 从NetApp Backup and Recovery菜单中，选择 *恢复*。
. 从名称搜索字段右侧的下拉列表中，选择 *Oracle*。
. 输入要还原的数据库的名称或筛选要还原的数据库所在的数据库主机。
+
出现符合您的搜索条件的快照列表。

. 选择要恢复的数据库的“*恢复*”按钮。
. 选择恢复选项：
+
[role="tabbed-block"]
====
.恢复到特定时间点
--
.. 选择*恢复到特定时间点*。
.. 选择“下一步”。
.. 从下拉菜单中选择一个日期，然后选择*搜索*。
+
显示指定日期的匹配快照列表。



--
.恢复到特定的系统变更号 (SCN)
--
.. 选择*恢复到特定的系统变更号 (SCN)*。
.. 选择“下一步”。
.. 输入要用作还原点的 SCN，然后选择*搜索*。
+
显示指定 SCN 的匹配快照列表。



--
.恢复到最新备份（上次良好状态）
--
.. 选择*恢复到最新备份*。
.. 选择“下一步”。
+
显示最新的完整备份和日志备份。



--
.从快照还原，无需恢复
--
.. 选择*从没有恢复的快照中恢复*。
.. 选择“下一步”。
+
显示匹配的快照。



--
====
. 选择快照源位置。
. 选择“下一步”继续。
. 选择恢复目标位置和设置：


[discrete]
===== 目的地选择

[role="tabbed-block"]
====
.恢复到原始位置
--
[NOTE]
====
如果将 PDB 或 PDB 表空间恢复到特定时间点或 SCN：

* 仅选择一个 PDB。时间点恢复与恢复多个 PDB 不兼容。
* PDB$SEED 无法选择进行时间点恢复。
* 控制文件还原不能与 PDB 或表空间的时间点恢复相结合。
* 确保数据备份和所需日志备份已编目。


====
. *目的地设置*：
. 选择要还原的内容：
+
** 选择*所有数据文件*以恢复整个数据库或容器数据库(CDB)。
** 选择 *Pluggable databases (PDBs)* 从 CDB 恢复一个或多个 PDB，而不影响容器中的其他 PDB。然后从列表中选择 PDB。
** 选择*可插拔数据库 (PDB) 表空间*（对于非 CDB 数据库显示为*表空间*）以恢复特定的 PDB 表空间。然后，选择 PDB 和表空间。


. （可选）启用*控制文件*选项以还原数据库控制文件。此选项不适用于 PDB 或 PDB 表空间的时间点或 SCN 恢复。
. （可选）启用 *Change database state if needed for restore and recovery* 选项，以允许 Backup and Recovery 根据恢复类型管理数据库状态。
. （可选）启用 *Force in place restore* 选项，以对 SAN/ASM 数据库使用更快的还原方法，从而跳过外来文件验证检查。数据库和 ASM 磁盘组将还原到备份创建点。
. 如果将 PDB 或 PDB 表空间恢复到特定时间点或 SCN，请指定外部归档日志文件位置。输入 RMAN 创建辅助实例以执行恢复的位置。输入以"/"开头的文件系统路径或以"+"开头的 ASM 磁盘组。使用文本输入字段旁边的"加号"和"减号"按钮添加或删除位置。
. （可选）启用 *Open the database or container database in READ-WRITE mode after recovery*，以便在恢复后以读写模式打开数据库。这会使已恢复的表空间联机。
. *前置脚本和后置脚本*：
+
** *Prescript*：（可选）启用此选项并输入应在还原操作之前运行的脚本的完整路径以及脚本所需的任何参数。
** *后记*：可选地，启用此选项并输入应在恢复操作后运行的脚本的完整路径以及该脚本所采用的任何参数。


. 为脚本选择超时值。如果脚本无法在此时间段内执行，则还原仍将继续。
. 选择*恢复*。


--
.恢复至备用位置
--
不适用于此预览版本中的 Oracle 数据库工作负载。

--
====