---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 您可以保护从本地ONTAP系统到 Amazon Web Services、Microsoft Azure、Google Cloud Platform 和StorageGRID 的Oracle 虚拟机，确保您的数据受到保护。 
---
= 保护 Oracle 数据库工作负载概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 NetApp Backup and Recovery 保护 Oracle 数据库和日志。获取快速、节省空间、故障一致和数据库一致的备份和恢复。将 Oracle Database 工作负载备份到 AWS S3、NetApp StorageGRID、Azure Blob Storage 或 ONTAP S3。将备份还原到本地 Oracle 主机。

使用NetApp Backup and Recovery实施 3-2-1 保护策略，其中您在 2 个不同的存储系统上拥有 3 个源数据副本，并在云中拥有 1 个副本。3-2-1 方法的优点包括：

* 多个数据副本可防止内部和外部网络安全威胁。
* 如果一种媒体发生故障，使用不同类型的媒体可以帮助您恢复。
* 您可以从现场副本快速恢复，如果现场副本受到损害，则可以使用异地副本。



NOTE: 要切换到NetApp Backup and Recovery UI 版本或从 NetApp Backup and Recovery UI 版本切换，请参阅link:br-start-switch-ui.html["切换到以前的NetApp Backup and RecoveryUI"]。

您可以使用 NetApp Backup and Recovery 执行以下与 Oracle 数据库工作负载相关的任务：

* link:br-start-discover-oracle.html["发现 Oracle Database 工作负载"]
* link:br-use-oracle-protection-groups.html["为 Oracle Database 工作负载创建和管理保护组"]
* link:br-use-oracle-backup.html["备份 Oracle Database 工作负载"]
* link:br-use-oracle-restore.html["还原 Oracle Database 工作负载"]

