---
sidebar: sidebar 
permalink: br-use-hyperv-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 您可以保护 Hyper-V 虚拟机，从本地ONTAP系统到主存储和二级存储，确保您的数据受到保护。 
---
= 通过 NetApp Backup and Recovery 保护 Hyper-V 工作负载
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 NetApp Backup and Recovery 备份和还原托管在 CIFS 共享上的独立 Hyper-V VM、故障转移群集实例和 SCVMM 预配的 VM。

您可以将 Hyper-V 工作负载备份到 Amazon S3 或 StorageGRID，并将其还原到本地 Hyper-V 主机。

使用 NetApp Backup and Recovery 实施 3-2-1 保护策略，在 2 个不同的存储系统上保留 3 个源数据副本，并在云中保留 1 个副本。3-2-1 方法的优势包括：

* 多个数据副本可防止内部和外部网络安全威胁。
* 多种媒体类型可确保在一种媒体类型发生物理或逻辑故障时能够进行故障转移。
* 现场副本可帮助您快速还原数据，如果现场副本受损，您可以使用非现场副本。


添加 Hyper-V 主机并发现资源时，NetApp Backup and Recovery 会在每个 Hyper-V 主机上安装 NetApp Hyper-V 插件和 NetApp SnapCenter Windows FileSystem 插件，以帮助管理和保护虚拟机。

您可以使用NetApp Backup and Recovery执行与 Hyper-V 工作负载相关的以下任务：

* link:br-start-discover-hyperv.html["发现 Hyper-V 工作负载"]
* link:br-use-hyperv-protection-groups.html["为 Hyper-V 工作负载创建和管理保护组"]
* link:br-use-hyperv-backup.html["备份 Hyper-V 工作负载"]
* link:br-use-hyperv-restore.html["恢复 Hyper-V 工作负载"]

