---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: '您可以从 Windows 客户操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。' 
---
= 恢复访客文件和文件夹的要求和限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 客户操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。



== 来宾还原工作流

客户操作系统还原操作包括以下步骤：

. 附
+
将虚拟磁盘附加到客户虚拟机并启动客户文件恢复会话。

. 等待
+
请等待附加操作完成，然后才能浏览和恢复。附加操作完成后，会自动创建一个访客文件恢复会话。

. 选择文件或文件夹
+
浏览 VMDK 文件，选择一个或多个文件或文件夹进行还原。

. 还原
+
将选定的文件或文件夹还原到指定位置。





== 恢复访客文件和文件夹的先决条件

在 Windows 客户操作系统上从 VMDK 还原文件或文件夹之前，请检查所有要求。

* 必须安装并运行 VMware 工具。
+
NetApp Backup and Recovery使用来自 VMware 工具的信息来建立与 VMware 客户操作系统的连接。

* Windows 客户操作系统必须运行 Windows Server 2008 R2 或更高版本。
+
有关受支持版本的最新信息，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。

* 目标虚拟机的凭据使用用户名为“Administrator”的内置域或本地管理员帐户。在开始恢复操作之前，请配置要附加虚拟磁盘的虚拟机的凭据。附加和恢复操作都需要凭据。工作组用户可以使用内置的本地管理员帐户。
+

IMPORTANT: 如果您必须使用非内置管理员帐户但在 VM 内具有管理权限的帐户，则必须在来宾 VM 上禁用 UAC。

* 您必须知道要从中恢复的备份快照和 VMDK。
+
NetApp Backup and Recovery不支持搜索文件或文件夹进行还原。开始之前，您必须知道快照中的文件或文件夹以及相应的 VMDK 的位置。

* 要附加的虚拟磁盘必须位于NetApp Backup and Recovery备份中。
+
包含要还原的文件或文件夹的虚拟磁盘必须位于使用NetApp Backup and Recovery执行的 VM 备份中。



* 对于名称非英文字母的文件，您必须将它们恢复到目录中，而不是作为单个文件。
+
您可以通过恢复文件所在的目录来恢复具有非字母名称的文件，例如日语汉字。





== 来宾文件还原限制

在从客户操作系统恢复文件或文件夹之前，您应该了解其功能限制。

* 您无法在来宾操作系统内恢复动态磁盘类型。
* 如果恢复加密的文件或文件夹，则不会保留加密属性。
* 您无法将文件或文件夹还原到加密文件夹。
* 隐藏的文件和文件夹会显示在文件浏览页面中，但您无法对其进行筛选。
* 您无法从 Linux 客户操作系统恢复。
+
您无法从运行 Linux 客户操作系统的 VM 还原文件和文件夹。但是，您可以附加 VMDK，然后手动恢复文件和文件夹。有关受支持的客户操作系统的最新信息，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。

* 您无法从 NTFS 文件系统还原到 FAT 文件系统。
+
当您尝试从 NTFS 格式还原为 FAT 格式时，不会复制 NTFS 安全描述符，因为 FAT 文件系统不支持 Windows 安全属性。

* 您无法从克隆的 VMDK 或未初始化的 VMDK 恢复客户文件。
* 您无法恢复文件的目录结构。
+
从嵌套目录恢复文件时，系统只会恢复文件本身，而不会恢复其目录结构。要恢复整个目录树，请复制顶层目录。

* 您无法将客户文件从 vVol VM 还原到备用主机。
* 您无法恢复加密的访客文件。

