---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: '您可以从 Windows 客户操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。' 
---
= 恢复访客文件和文件夹的要求和限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 或 Linux 来宾操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。



== 来宾还原工作流

客户操作系统还原操作包括以下步骤：

. 附
+
将虚拟磁盘连接到来宾 VM 或代理 VM，并启动来宾文件还原会话。

. 等待
+
请等待附加操作完成，然后才能浏览和恢复。附加操作完成后，会自动创建一个访客文件恢复会话。

. 选择文件或文件夹
+
浏览或搜索虚拟磁盘文件，并选择一个或多个要还原的文件或文件夹。

. 还原
+
将选定的文件或文件夹还原到指定位置。





== 恢复访客文件和文件夹的先决条件

在从 VMDK 还原文件或文件夹之前，请查看所有要求。

* 必须安装并运行 VMware 工具。
+
NetApp Backup and Recovery 使用来自 VMware 工具的信息来建立与 VMware 来宾操作系统的连接。

* 您必须知道要从中恢复的备份快照和 VMDK。
* 要附加的虚拟磁盘必须位于NetApp Backup and Recovery备份中。
+
包含要还原的文件或文件夹的虚拟磁盘必须位于使用NetApp Backup and Recovery执行的 VM 备份中。

* 要使用代理 VM，必须配置代理 VM。
+
如果要将虚拟磁盘连接到代理 VM，必须在连接和还原操作开始之前配置代理 VM。

* 对于名称非英文字母的文件，您必须将它们恢复到目录中，而不是作为单个文件。
+
您可以通过恢复文件所在的目录来恢复具有非字母名称的文件，例如日语汉字。



有关访客操作系统支持的最新信息，请参见  https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。



=== Windows 客户机

* Windows 客户操作系统必须运行 Windows Server 2008 R2 或更高版本。
+
有关受支持版本的最新信息，请参阅 https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。

* 目标虚拟机的凭据使用用户名为“Administrator”的内置域或本地管理员帐户。在开始恢复操作之前，请配置要附加虚拟磁盘的虚拟机的凭据。附加和恢复操作都需要凭据。工作组用户可以使用内置的本地管理员帐户。
+

IMPORTANT: 如果您必须使用非内置管理员帐户但在 VM 内具有管理权限的帐户，则必须在来宾 VM 上禁用 UAC。





=== Linux 客户机

* 支持以下来宾操作系统发行版：
+
** Red Hat Enterprise Linux
** Ubuntu
** Debian


* Run-As 帐户需要 root 或 sudo 权限。
* 对于跨虚拟机还原（还原到其他 Linux 虚拟机），SSH 必须在目标虚拟机上运行。




== 来宾文件还原限制

在从客户操作系统恢复文件或文件夹之前，您应该了解其功能限制。

* 您无法在来宾操作系统内恢复动态磁盘类型。
* 如果恢复加密的文件或文件夹，则不会保留加密属性。
* 您无法将文件或文件夹还原到加密文件夹。
* 隐藏的文件和文件夹会显示在文件浏览页面中，但您无法对其进行筛选。
* 不能在不同操作系统的来宾之间还原文件或文件夹（还原到不同的 VM 时，目标 OS 类型必须与源 OS 类型相同）。
* 您无法从 NTFS 文件系统还原到 FAT 文件系统。
+
当您尝试从 NTFS 格式还原为 FAT 格式时，不会复制 NTFS 安全描述符，因为 FAT 文件系统不支持 Windows 安全属性。

* 您无法从克隆的 VMDK 或未初始化的 VMDK 恢复客户文件。
* 您无法恢复文件的目录结构。
+
从嵌套目录恢复文件时，系统只会恢复文件本身，而不会恢复其目录结构。要恢复整个目录树，请复制顶层目录。

* 您无法将客户文件从 vVol VM 还原到备用主机。
* 您无法恢复加密的访客文件。

