---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 通过验证操作环境、控制台代理和控制台帐户的准备情况来开始使用NetApp Backup and Recovery 。要使用NetApp Backup and Recovery，您需要满足这些先决条件。 
---
= NetApp Backup and Recovery 要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在开始使用 NetApp Backup and Recovery 之前，请确保您的 NetApp Console 和操作环境满足以下要求。



[[prepare-netapp-console]]
== 准备 NetApp Console

您可以通过 NetApp Console 访问 NetApp Backup and Recovery。要准备 Console 以进行 Backup and Recovery，您必须：

* 添加 Console 代理
* 至少添加一个存储系统
* 配置 Console 组织和用户角色


您需要 NetApp Console 中的组织管理员或超级管理员角色才能完成此准备工作。

要了解有关 NetApp Console 的更多信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["用于统一存储管理的 NetApp Console"^]。



[[complete-initial-netapp-console-setup]]
=== 完成初始 NetApp Console 设置

如果您尚未完成 NetApp Console 的初始设置，请完成此操作。

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["NetApp Console (SaaS 应用程序) 入门工作流程"^]



[[deploy-a-console-agent]]
=== 部署 Console 代理

Console 代理是您在网络中安装的轻量级软件组件，用于将存储基础架构连接到 NetApp Console。它实现了高级存储编排、数据服务和安全的云集成。

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解控制台代理"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["部署 Console 代理"^]



[[add-a-storage-system]]
=== 添加存储系统

在使用 Backup and Recovery 保护工作负载之前，您需要将 ONTAP 存储系统添加到 Console。

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["在 NetApp Console 中发现本地 ONTAP 集群"^]



[[configure-an-organization-and-user-roles]]
=== 配置组织和用户角色

了解组织、项目和用户角色，然后为用户配置执行其任务所需的适当权限。

有关使用组织和项目控制资源访问的信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["向 NetApp Console 组织添加用户"]。

有关在 NetApp Backup and Recovery 中执行操作所需的角色和权限的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console中的NetApp Backup and Recovery角色"]。



[[requirements-for-backups-to-object-storage]]
== 对象存储备份的要求

要将对象存储用作备份目标，需要具有 AWS S3、Google Cloud Storage、Microsoft Azure Blob、StorageGRID 或 ONTAP 的帐户并配置适当的访问权限。



[[requirements-for-protecting-ontap-volume-workloads]]
== 保护 ONTAP 卷工作负载的要求

要对 ONTAP 卷工作负载使用 NetApp Backup and Recovery，需要满足以下主机系统、空间和大小调整先决条件。

* 需要 ONTAP 9.8 或更高版本。
* ONTAP 9.12.1 或更高版本是 FlexGroup 卷保护的必要条件。有关详细信息，请参见 link:br-reference-limitations.html["NetApp Backup and Recovery for ONTAP卷的已知限制"]。
* 备份或还原到与 S3 兼容的对象存储需要 ONTAP 9.17.1 或更高版本。
* 要跨不同云提供商支持每个系统超过 6 个存储桶（最多 100 个存储桶），需要 ONTAP 9.19.1 或更高版本。
* 本地 ONTAP 实例上必须已启用 ONTAP One 许可证。


有关受支持的功能、卷类型、备份和还原目标等信息，请参阅 link:prev-ontap-protect-overview.html["保护您的ONTAP卷数据"]。



[[requirements-for-protecting-microsoft-sql-server-workloads]]
== 保护 Microsoft SQL Server 工作负载的要求

要将NetApp Backup and Recovery用于 Microsoft SQL Server 工作负载，您需要满足以下主机系统、空间和大小调整前提条件。


NOTE: 要跨不同云提供商支持每个系统超过 6 个存储桶（最多 100 个存储桶），需要 ONTAP 9.19.1 或更高版本。

[cols="33,66a"]
|===
| 物品 | 要求 


| 操作系统  a| 
Microsoft Windows 有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 互操作性表工具"^]。



| Microsoft SQL Server 版本  a| 
VMware 虚拟机文件系统 (VMFS) 和 VMware 虚拟机磁盘 (VMDK) NFS 支持 2012 及更高版本。



| SnapCenter服务器版本  a| 
如果要将现有数据从SnapCenter导入NetApp Backup and Recovery ，则需要SnapCenter Server 5.0 或更高版本。


NOTE: 如果您已经拥有SnapCenter，请先检查以确保在从SnapCenter导入之前已满足先决条件。看link:concept-start-prereq-snapcenter-import.html["从SnapCenter导入资源的先决条件"]。



| SQL Server 主机上插件的最小 RAM  a| 
1 GB



| SQL Server 主机上插件的最小安装和日志空间  a| 
5 GB

分配足够的磁盘空间并监控日志文件夹的存储消耗。所需的日志空间取决于执行的备份次数和数据保护操作的频率。如果没有足够的空间，则不会为操作创建日志。



| 所需的软件包  a| 
* ASP.NET Core Runtime 8.0.24 托管捆绑包（以及所有后续的 8.0.x 修补程序）
* PowerShell 7.4.13


有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 互操作性表工具"^]。

|===
[cols="33,66a"]
|===
| 数据库主机 | 支持的存储 


| 物理服务器  a| 
* 通过光纤通道呈现的 LUN
* 通过 iSCSI 呈现的 LUN




| VMware VM  a| 
* 通过 iSCSI 启动程序直接连接到来宾系统的 iSCSI LUN
* 虚拟机文件系统 (VMFS)
* NFS 数据存储库




| Hyper-V 虚拟机  a| 
通过 iSCSI 启动程序直接连接到来宾系统的 iSCSI LUN


NOTE: 不支持保护存储在 NetApp 存储上设置的直通磁盘或 VHD/VHDX 文件中的数据库。

|===


[[requirements-for-protecting-vmware-workloads]]
== 保护 VMware 工作负载的要求

您需要特定的要求来发现和保护您的 VMware 工作负载。

|===
| 需求 | 支持 


| 数据存储库类型 | NFSv3、NFSv4.1 和 VMFS 


| VMware ESXi Server 版本 | 7.0U1 及更高版本 


| VMware vCenter vSphere 版本 | 7.0U1 及更高版本 


| VMware Tools | 使用文件和文件夹还原功能以及 VM 一致性备份时，需要使用 VMware Tools。要确保 VMware Tools 版本与您的 ESXi Server 版本相匹配，请参见 https://packages.vmware.com/tools/versions["VMware 版本映射信息"]。 


| IP 地址类型 | IPv4，IPv6 


| VMware TLS 版本 | 1.2, 1.3 


| 已连接存储  a| 
* ONTAP 9.13.1 或更高版本（需要 ONTAP 9.19.1 或更高版本才能支持跨不同云提供商的每个系统超过 6 个存储桶；最多 100 个存储桶）
* 运行 9.13.1 或更高版本的 Amazon FSx for NetApp ONTAP 存储系统
* ASA r2 仅限 SAN 系统（需要 ONTAP 9.17.1 或更高版本）


|===
[cols="33,66a"]
|===
| 端口类型 | 预配置端口 


| VMware ESXi 服务器端口  a| 
443 (HTTPS)，双向。文件和文件夹还原功能使用此端口。



| 存储集群或存储虚拟机端口  a| 
* 443 (HTTPS)，双向。
* 80 (HTTP)，双向。此端口用于在虚拟设备与存储 VM 或包含存储 VM 的集群之间进行通信。


|===
.用于保护 VMware 工作负载的基于角色的访问控制 (RBAC) 要求
您的 Console 用户帐户需要具有 Backup and Recovery 超级管理员角色才能处理 VMware 工作负载。

有关 Backup and Recovery 角色的详细信息，请参阅 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console 中的备份和恢复角色"]。



[[requirements-for-protecting-kvm-workloads]]
== 保护 KVM 工作负载的要求

您需要特定的要求来发现和保护 KVM 虚拟机。


NOTE: 要跨不同云提供商支持每个系统超过 6 个存储桶（最多 100 个存储桶），需要 ONTAP 9.19.1 或更高版本。

* 运行内核版本 5.14.0-503.22.1.el9_5.x86_64（长期）或更高版本的现代 Linux 发行版
* 您的 KVM 主机和虚拟机必须由管理平台进行管理。NetApp Backup and Recovery支持以下管理平台：
+
** Apache CloudStack 4.22.0.0


* 确保允许从控制台代理到 KVM 主机的入站网络流量到达端口 22。
* QEMU Guest Agent 版本 9.0.0 或更高版本
* libvirt 版本 10.5.0 或更高版本



NOTE: 为确保 KVM 工作负载恢复成功完成，请确保在用于 KVM 备份的保护策略中启用“启用 VM 一致性快照”设置。

[NOTE]
====
要启用对非 root 用户管理的 KVM 虚拟机的保护，请按以下步骤操作：

. 将卷挂载为 NFS3 类型，以避免使用 `nobody` 用户和组。
. 使用以下命令将非root用户添加到 `qemu` 在保留现有群体的同时，组建新的群体：
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. 使用以下命令将挂载路径的所有权授予…… `qemu` 用户和组，并更改挂载路径的权限：
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. 如果存在 NetApp_SnapCenter_Backups 目录，请将其删除。


====


[[requirements-for-protecting-oracle-database-workloads]]
== 保护 Oracle Database 工作负载的要求

确保您的环境满足特定要求，以发现和保护 Oracle Database 资源。


NOTE: 要跨不同云提供商支持每个系统超过 6 个存储桶（最多 100 个存储桶），需要 ONTAP 9.19.1 或更高版本。

|===
| 需求 | 支持 


| 部署拓扑  a| 
* 独立（NFS、SAN、ASM SAN）
* 基于 ASM 的 RAC（VMFS 上的 VMDK）




| Oracle 数据库版本  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| 数据库存储 | 必须部署在 NetApp ONTAP（主要或次要） 


| 主机操作系统  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| 对象存储（备份目标）  a| 
* Azure 对象存储
* 亚马逊 AWS
* NetAppStorageGRID
* ONTAP S3


|===


[[requirements-for-protecting-kubernetes-applications]]
== 保护 Kubernetes 应用程序的要求

您需要特定的要求来发现 Kubernetes 资源并保护您的 Kubernetes 应用程序。

有关 NetApp Console 要求，请参阅 <<准备 NetApp Console>>。


NOTE: 要跨不同云提供商支持每个系统超过 6 个存储桶（最多 100 个存储桶），需要 ONTAP 9.19.1 或更高版本。


NOTE: NetApp 强烈建议为用于 Kubernetes 工作负载的 Console 代理分配静态 IP 地址，以避免代理 IP 地址更改时出现问题。

* 主 ONTAP 系统（不支持 ASA r2 系统）
* NetApp Trident 25.02 或更高版本
* NetApp Trident Protect 26.05 或更高版本（在发现期间安装在 Kubernetes 集群上）
* Kubernetes 集群 - 支持的 Kubernetes 发行版和版本包括  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"] 支持的发行版和版本。
+
** 确保 TCP 端口 443 在 Kubernetes 集群、Trident Protect Connector 和 Trident Protect 代理之间的出站方向上未过滤。






[[requirements-for-protecting-hyper-v-workloads]]
== 保护 Hyper-V 工作负载的要求

确保您的 Hyper-V 实例满足发现和保护虚拟机的特定要求。

|===
| 需求 | 支持 


| Microsoft Hyper-V | 2019、2022 和 2025 版本 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle（以及所有后续的 8.0.x 补丁） 


| PowerShell | 7.4.13 或更高版本 


| 如果非管理员用户将保护 Hyper-V VM，请确保用户具有以下权限  a| 
* 本地管理员组的成员
* "作为服务登录"本地安全策略的一部分




| 确保在 Windows 防火墙设置中允许以下端口的双向 HTTPS 流量  a| 
* TCP 8144（NetApp Plugin for Hyper-V）
* TCP 8145（NetApp Plugin for Windows）




| 已连接存储  a| 
* ONTAP 9.13.1 或更高版本
* SMB 共享
* 通过 iSCSI 或光纤通道连接的 SAN 存储


|===
.Hyper-V 主机的硬件要求
* 支持独立主机和 FCI 集群主机
* Hyper-V 主机上的NetApp Hyper-V 插件至少需要 1GB RAM
* Hyper-V 主机上插件的最低安装和日志空间为 5GB
+

NOTE: 确保在 Hyper-V 主机上为日志文件夹分配足够的磁盘空间并定期监控其使用情况。所需空间取决于备份和数据保护操作发生的频率。如果空间不足，则不会生成日志。



.NetApp ONTAP 配置要求
* 主 ONTAP 系统（ONTAP 9.14.1 或更高版本 - 需要 ONTAP 9.19.1 或更高版本才能支持跨不同云提供商每个系统超过 6 个存储桶；最多 100 个存储桶）
* 对于使用 SMB 共享存储虚拟机数据的 Hyper-V 部署，请确保在 ONTAP 系统上启用连续可用性共享属性。有关说明，请参阅 https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["ONTAP 文档"^]。

