---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 使用 NetApp Backup and Recovery 保护您的 VMware 工作负载。 
---
= 使用 NetApp Backup and Recovery 将本地 ONTAP 数据备份到 S3 兼容存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
完成 NetApp Backup and Recovery 中的几个步骤，开始从主要本地 ONTAP 系统备份卷数据。您可以将备份发送到辅助 ONTAP 存储系统（复制的卷）或发送到与 S3 兼容的存储系统上的存储桶，或两者兼而有之。



[[verify-support-for-your-configuration]]
== 验证对您的配置的支持

在开始将卷备份到 S3 兼容存储之前，请阅读以下要求，以确保您具有受支持的配置。

支持的 ONTAP 版本:: 需要最低 ONTAP 版本 9.17.1。




[[supported-actions]]
=== 支持的操作

以下是备份到 S3 兼容存储时支持的操作：

* 将崩溃一致性和应用一致性快照从本地 ONTAP 备份到第三方 S3 兼容对象存储
* 核心数据保护工作流：备份、还原和备份删除
* 已使用 Wasabi 对象存储进行测试和验证；客户还报告了使用 MinIO 和 IBM Cloud Object Storage 的成功部署
* NetApp 支持接受和分类涉及第三方 S3 兼容对象存储的所有支持请求




[[unsupported-features-and-configurations]]
=== 不支持的功能和配置

备份到 S3 兼容存储时不支持以下功能和配置：

* 不支持自带存储桶 (BYOB)
* 备份策略中的 DataLock 启用不受支持
* 备份策略中不支持启用存档模式
* 不支持存储桶级加密选项
* 不支持 MetroCluster 配置
* 不支持基于云的 ONTAP 环境—仅支持本地 ONTAP




[[caveats]]
=== 注意事项

备份到 S3 兼容存储时，请记住以下几点：

* *性能无法保证*：NetApp 产品对 S3 API 延迟和 IOPS 敏感。第三方对象存储必须提供 AWS S3 等效延迟和 IOPS，以实现可比性能。NetApp 不对对象存储性能进行故障排除。
* *对数据损坏或丢失不承担任何责任*：NetApp 对第三方 S3 对象存储问题导致的数据丢失或服务停机不承担任何责任。
* *有限功能支持*：第三方 S3 兼容目标支持的功能集是本机目标（AWS S3、Azure Blob、GCP、ONTAP S3、StorageGRID）可用功能的子集。




[[prepare-your-console-agent]]
== 准备控制台代理

控制台代理是控制台功能的主要软件。需要控制台代理来备份和恢复您的ONTAP数据。



[[create-or-switch-console-agents]]
=== 创建或切换控制台代理

将数据备份到 S3 兼容存储时，必须在您的本地或云端提供 Console 代理。您需要安装新的 Console 代理，或确保当前选择的 Console 代理位于这些位置之一。本地 Console 代理可以安装在有或没有互联网访问的站点中。

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["了解控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["在您的云环境中安装控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["在具有互联网访问权限的 Linux 主机上安装控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["在没有互联网访问的 Linux 主机上安装控制台代理"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["在控制台代理之间切换"^]




[[prepare-console-agent-networking-requirements]]
=== 准备控制台代理网络要求

确保安装控制台代理的网络启用以下连接：

* 通过端口 443 到 S3 兼容服务器的 HTTPS 连接
* 通过端口 443 建立到源ONTAP集群管理 LIF 的 HTTPS 连接
* 通过端口 443 到NetApp Backup and Recovery 的出站互联网连接（当控制台代理安装在“暗站”时不需要）




==== 私人模式（暗站）注意事项

NetApp Backup and Recovery功能内置于控制台代理中。当以私人模式安装时，您需要定期更新控制台代理软件才能访问新功能。检查link:whats-new.html["NetApp Backup and Recovery新功能"]查看每个NetApp Backup and Recovery版本中的新功能。当您想要使用新功能时，请按照以下步骤操作 https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["升级控制台代理软件"^]。

当您在标准 SaaS 环境中使用 NetApp Backup and Recovery 时，NetApp Backup and Recovery 配置数据将备份到云中。当您在没有互联网访问的站点中使用 NetApp Backup and Recovery 时，NetApp Backup and Recovery 配置数据将备份到存储备份的 S3 兼容存储区。



[[verify-license-requirements]]
== 验证许可证要求

在为集群激活NetApp Backup and Recovery之前，您需要从NetApp购买并激活NetApp Backup and Recovery BYOL 许可证。该许可证用于备份和恢复对象存储 - 创建快照或复制卷不需要许可证。此许可证适用于该帐户，可跨多个系统使用。

您需要NetApp提供的序列号，以便您在许可证的有效期和容量内使用该服务。link:br-start-licensing.html["了解如何管理您的 BYOL 许可证"]。


TIP: 将文件备份到 S3 兼容存储时，不支持 PAYGO 许可。



[[prepare-your-ontap-clusters]]
== 准备ONTAP集群

准备源本地ONTAP系统和任何辅助本地ONTAP或Cloud Volumes ONTAP系统。

准备ONTAP集群涉及以下步骤：

* 在NetApp Console中发现您的ONTAP系统
* 验证ONTAP系统要求
* 验证ONTAP网络要求以将数据备份到对象存储
* 验证ONTAP复制卷的网络要求




[[discover-your-ontap-systems-in-netapp-console]]
=== 在NetApp Console中发现您的ONTAP系统

您的源本地ONTAP系统和任何辅助本地ONTAP或Cloud Volumes ONTAP系统都必须在NetApp Console*系统* 页面上可用。

您需要知道集群管理 IP 地址和管理员用户帐户的密码才能添加集群。https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["了解如何发现集群"^]。



[[verify-ontap-system-requirements]]
=== 验证ONTAP系统要求

确保您的ONTAP系统满足以下要求：

* 最低版本为ONTAP 9.8；建议使用ONTAP 9.8P13 及更高版本。
* SnapMirror许可证（包含在高级捆绑包或数据保护捆绑包中）。
+
*注意：*使用NetApp Backup and Recovery时不需要“混合云捆绑包”。

+
了解如何 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理您的集群许可证"^]。

* 时间和时区设置正确。了解如何 https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["配置集群时间"^]。
* 如果您复制数据，请检查源系统和目标系统是否运行兼容的ONTAP版本。
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["查看与SnapMirror关系兼容的ONTAP版本"^]。





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== 验证ONTAP网络要求以将数据备份到对象存储

您必须确保连接到对象存储的系统满足以下要求。

[NOTE]
====
* 当您使用扇出备份架构时，必须在主存储系统上配置设置。
* 当您使用级联备份架构时，必须在_辅助_存储系统上配置设置。
+
link:prev-ontap-protect-journey.html["了解有关备份架构类型的更多信息"]。



====
需要满足以下ONTAP集群网络要求：

* ONTAP 集群通过用户指定的端口从集群间 LIF 向 S3 兼容服务器发起 HTTPS 连接，以执行备份和还原操作。端口可在备份设置期间进行配置。
+
ONTAP从对象存储中读取和写入数据。对象存储从不启动，它只是响应。

* ONTAP需要从控制台代理到集群管理 LIF 的入站连接。
* 每个托管要备份的卷的ONTAP节点上都需要一个集群间 LIF。  LIF 必须与ONTAP用于连接对象存储的 _IPspace_ 相关联。 https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["了解有关 IP 空间的更多信息"^] 。
+
当您设置NetApp Backup and Recovery时，系统会提示您输入要使用的 IP 空间。您应该选择与每个 LIF 关联的 IP 空间。这可能是“默认” IP 空间或您创建的自定义 IP 空间。

* 节点的集群间 LIF 能够访问对象存储（当控制台代理安装在“暗”站点中时不需要）。
* 已为卷所在的存储虚拟机配置 DNS 服务器。了解如何 https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["为 SVM 配置 DNS 服务"^]。
* 如果使用的 IPspace 不同于 Default，则可能需要创建静态路由才能访问对象存储。
* 如有必要，请更新防火墙规则，以允许NetApp Backup and Recovery服务通过您指定的端口（通常为端口 443）从ONTAP连接到对象存储，并通过端口 53（TCP/UDP）从存储虚拟机到 DNS 服务器的名称解析流量。




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== 验证ONTAP复制卷的网络要求

如果您计划使用NetApp Backup and Recovery在辅助ONTAP系统上创建复制卷，请确保源系统和目标系统满足以下网络要求。

* 如果集群位于本地，则您应该从公司网络连接到云提供商中的虚拟网络。这通常是 VPN 连接。
* ONTAP集群必须满足额外的子网、端口、防火墙和集群要求。




[[activate-backups-on-your-ontap-volumes]]
== 激活ONTAP卷上的备份

随时直接从您的本地系统激活备份。

向导将引导您完成以下主要步骤：

* 选择要备份的卷
* 定义备份策略和政策
* 检查您的选择


您还可以<<显示 API 命令>>在审查步骤中，您可以复制代码来自动为未来的系统激活备份。



[[start-the-wizard]]
=== 启动向导

.步骤
. 使用以下方式之一访问激活备份和恢复向导：
+
** 从控制台*系统*页面中，选择系统，然后选择右侧面板中备份和恢复旁边的*启用>备份卷*。
** 在备份和恢复栏中选择*卷*。从“卷”选项卡中，选择“操作 (...)”选项，然后为单个卷（尚未启用复制或备份到对象存储）选择“激活备份”。


+
向导的简介页面显示了保护选项，包括本地快照、复制和备份。如果您在此步骤中选择了第二个选项，则会出现“定义备份策略”页面，其中选择一个卷。

. 继续以下选项：
+
** 如果您已经有控制台代理，那么一切就绪了。只需选择*下一步*。
** 如果您没有控制台代理，则会出现“添加控制台代理”选项。参考<<准备控制台代理>>。






[[select-the-volumes-that-you-want-to-back-up]]
=== 选择要备份的卷

选择您想要保护的卷。受保护的卷是具有以下一项或多项的卷：快照策略、复制策略、备份到对象策略。

您可以选择保护FlexVol或FlexGroup卷；但是，在激活系统备份时不能选择这些卷的混合。了解如何link:prev-ontap-backup-manage.html["激活系统中附加卷的备份"]（FlexVol或FlexGroup）在为初始卷配置备份后。

[NOTE]
====
* 您一次只能在单个FlexGroup卷上激活备份。
* 在选择要保护的源卷时，只能选择具有匹配 SnapLock 设置的卷。您选择的卷必须全部启用 SnapLock 功能，或者全部禁用 SnapLock 功能。


====
.步骤
请注意，如果您选择的卷已经应用了快照或复制策略，那么您稍后选择的策略将覆盖这些现有策略。

. 在“选择卷”页面中，选择要保护的一个或多个卷。
+
** 或者，过滤行以仅显示具有特定卷类型、样式等的卷，以便更轻松地进行选择。
** 选择第一个卷后，您可以选择所有FlexVol卷（FlexGroup卷一次只能选择一个）。要备份所有现有的FlexVol卷，请先选中一个卷，然后选中标题行中的框。
** 要备份单个卷，请选中每个卷对应的复选框。


. 选择“下一步”。




[[define-the-backup-strategy]]
=== 定义备份策略

定义备份策略涉及配置以下选项：

* 保护选项：您是否要实施一个或所有备份选项：本地快照、复制和备份到对象存储
* 架构：您是否要使用扇出式或级联备份架构
* 本地快照策略
* 复制目标和策略
* 备份到对象存储信息（提供商、加密、网络、备份策略和导出选项）。


.步骤
. 在“定义备份策略”页面中，选择以下一项或全部。默认情况下，所有三个都被选中：
+
** *本地快照*：创建本地快照。
** *复制*：在另一个ONTAP存储系统上创建复制卷。
** *备份*：将卷备份到为 S3 配置的ONTAP系统上的存储桶。


. *架构*：如果您同时选择了复制和备份，请选择以下信息流之一：
+
** *级联*：备份数据从主系统流向辅助系统，然后从辅助系统流向对象存储。
** *扇出*：备份数据从主系统流向辅助系统，并从主系统流向对象存储。
+
有关这些架构的详细信息，请参阅link:prev-ontap-protect-journey.html["规划您的保护之旅"]。



. *本地快照*：选择现有的快照策略或创建新的快照策略。
+

TIP: 如果要在激活快照之前创建自定义策略，则可以使用 System Manager 或ONTAP CLI `snapmirror policy create`命令。参考。

+

TIP: 要使用备份和恢复创建自定义策略，请参阅link:br-use-policies-create.html["创建策略"]。

+
要创建策略，请选择“创建新策略”并执行以下操作：

+
** 输入策略的名称。
** 选择最多五个时间表，通常频率不同。
** 选择“*创建*”。


. *复制*：如果选择了*复制*，请设置以下选项：
+
** *复制目标*：选择目标系统和存储 VM。可选择目标聚合（或 FlexGroup 卷的聚合）以及将添加到复制卷名称的前缀或后缀。
** *复制策略*：选择现有的复制策略或创建新的复制策略。
+
要创建策略，请选择“创建新策略”并执行以下操作：

+
*** 输入策略的名称。
*** 选择最多五个时间表，通常频率不同。
*** 选择“*创建*”。




. *备份到对象*：如果您选择了*备份*，请设置以下选项：
+
** *提供商*：选择* ONTAP S3*。
** *提供商设置*：输入 S3 服务器 FQDN 详细信息、端口以及用户的访问密钥和密钥。
+
访问密钥和密钥用于您创建的用户，以授予ONTAP集群对 S3 存储桶的访问权限。

** *网络*：选择要备份的卷所在的源ONTAP集群中的 IP 空间。此 IP 空间的集群间 LIF 必须具有出站互联网访问权限（当控制台代理安装在“暗站”中时不需要）。
+

TIP: 选择正确的 IP 空间可确保NetApp Backup and Recovery可以建立从ONTAP到ONTAP S3 对象存储的连接。

** *备份策略*：选择现有的备份策略或创建新的备份策略。
+

TIP: 您可以使用 System Manager 或ONTAP CLI 创建策略。使用ONTAP CLI 创建自定义策略 `snapmirror policy create`命令，请参阅。

+

TIP: 要使用备份和恢复创建自定义策略，请参阅link:br-use-policies-create.html["创建策略"]。

+
要创建策略，请选择“创建新策略”并执行以下操作：

+
*** 输入策略的名称。
*** 选择最多五个时间表，通常频率不同。
*** 对于备份到对象策略，请设置 Datalock 和 Ransomware 保护设置。有关 Datalock 和 Ransomware 保护的详细信息，请参阅 link:prev-ontap-policy-object-options.html["备份到对象策略设置"]。
*** 选择“*创建*”。


** *将现有快照导出到对象存储作为备份文件*：如果此系统中存在与您刚刚选择的备份计划标签（例如，每日、每周等）匹配的卷的本地快照，则会显示此附加提示。选中此框可将所有历史快照复制到对象存储作为备份文件，以确保对您的卷进行最全面的保护。


. 选择“下一步”。




[[review-your-selections]]
=== 检查您的选择

这是审查您的选择并在必要时进行调整的机会。

.步骤
. 在“审核”页面中，审核您的选择。
. （可选）选中复选框*自动将快照策略标签与复制和备份策略标签同步*。这将创建具有与复制和备份策略中的标签匹配的标签的快照。如果策略不匹配，则不会创建备份。
. 选择*激活备份*。


.结果
NetApp Backup and Recovery开始对您的卷进行初始备份。复制卷和备份文件的基线传输包括源数据的完整副本。后续传输包含快照中包含的主存储数据的差异副本。

在目标集群中创建一个复制卷，该卷将与主存储卷同步。

在您输入的 S3 访问密钥和密钥指示的服务帐户中创建一个 S3 存储桶，并将备份文件存储在那里。

显示卷备份仪表板，以便您可以监控备份的状态。

您还可以使用link:br-use-monitor-tasks.html["作业监控页面"]。



[[show-the-api-commands]]
=== 显示 API 命令

您可能想要显示并选择性地复制激活备份和恢复向导中使用的 API 命令。您可能希望这样做以便在未来的系统中自动激活备份。

.步骤
. 从激活备份和恢复向导中，选择*查看 API 请求*。
. 要将命令复制到剪贴板，请选择*复制*图标。

