---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery支持一个 Google 归档存储类和大多数区域。 
---
= NetApp Backup and Recovery支持 Google 归档存储层
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用此信息了解 NetApp Backup and Recovery 支持的 Google Cloud Storage 存档层。您还可以查看已存档备份的恢复成本和检索时间。



[[supported-google-archival-storage-classes-for-netapp-backup-and-recovery]]
== NetApp Backup and Recovery支持的 Google 归档存储类

最初创建备份文件时，它们存储在 _Standard_ 存储中。此层针对存储不常访问的数据进行了优化，但仍允许即时访问。

如果您的本地集群使用的是 ONTAP 9.12.1 或更高版本，则可以选择在一定天数（通常超过 30 天）后在 NetApp Backup and Recovery UI 中将较旧的备份分层到 _Archive_ 存储，以进一步优化成本。此层中的数据需要更高的检索成本，因此您需要考虑从这些已存档备份文件还原数据的频率。请参阅本页有关从存档存储还原数据的部分。

请注意，当您使用此类生命周期规则配置NetApp Backup and Recovery时，在 Google 帐户中设置存储桶时不得配置任何生命周期规则。

https://cloud.google.com/storage/docs/storage-classes["了解 Google 存储类别"^]。



[[restore-data-from-archival-storage]]
== 从档案存储中恢复数据

虽然将较旧的备份文件存储在存档存储中比标准存储便宜得多，但从存档存储中的备份文件中访问数据进行恢复操作将花费更长的时间并且花费更多。

从 Google Archive 恢复数据需要多少钱？:: 要了解按地区划分的 Google Cloud Storage 详细定价，请访问 https://cloud.google.com/storage/pricing["Google Cloud Storage 定价页面"^]。
恢复我在 Google Archive 中存档的对象需要多长时间？:: 总还原时间由两部分组成：
+
--
* *检索时间*：从存档中检索备份文件并将其放置在标准存储中的时间。这有时被称为“补水”时间。与其他云提供商提供的“最冷”存储解决方案不同，您的数据可以在几毫秒内访问。
* *恢复时间*：从标准存储中的备份文件恢复数据的时间。这次与不使用存档层时直接从标准存储进行的典型恢复操作没有什么不同。


--

