---
sidebar: sidebar 
permalink: prev-reference-aws-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery支持两种 S3 存档存储类和大多数区域。 
---
= NetApp Backup and Recovery支持的 AWS 存档存储层
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery支持两种 S3 存档存储类和大多数区域。

[]
====

NOTE: 要切换到NetApp Backup and Recovery UI 版本或从 NetApp Backup and Recovery UI 版本切换，请参阅link:br-start-switch-ui.html["切换到以前的NetApp Backup and RecoveryUI"]。

====


== NetApp Backup and Recovery支持的 S3 归档存储类

最初创建备份文件时，它们存储在 S3 _Standard_ 存储中。此层针对存储不经常访问的数据进行了优化；但也允许您立即访问它。  30 天后，备份将转换为 S3_标准-不频繁访问_存储类以节省成本。

如果您的源集群运行的是ONTAP 9.10.1 或更高版本，您可以选择在一定天数（通常超过 30 天）后将备份分层到 _S3 Glacier_ 或 _S3 Glacier Deep Archive_ 存储，以进一步优化成本。您可以将其设置为“0”或 1-999 天。如果将其设置为“0”天，则以后不能将其更改为1-999天。

这些层中的数据在需要时无法立即访问，并且需要更高的检索成本，因此您需要考虑可能需要多久从这些存档的备份文件中恢复数据。请参阅此页面上有关从档案存储恢复数据的部分。

* 如果您在激活NetApp Backup and Recovery时在第一个备份策略中未选择任何存档层，那么 _S3 Glacier_ 将是您未来策略的唯一存档选项。
* 如果您在第一个备份策略中选择了“S3 Glacier”，那么您可以将该集群的未来备份策略更改为“S3 Glacier Deep Archive”层。
* 如果您在第一个备份策略中选择“S3 Glacier Deep Archive”，则该层将是该集群未来备份策略唯一可用的存档层。


请注意，当您使用此类生命周期规则配置NetApp Backup and Recovery时，在 AWS 帐户中设置存储桶时不得配置任何生命周期规则。

https://aws.amazon.com/s3/storage-classes/["了解 S3 存储类别"^]。



== 从档案存储中恢复数据

虽然将较旧的备份文件存储在档案存储中比标准或标准 IA 存储便宜得多，但从档案存储中的备份文件中访问数据进行恢复操作将花费更长的时间并且花费更多。

从 Amazon S3 Glacier 和 Amazon S3 Glacier Deep Archive 恢复数据需要多少费用？:: 从 Amazon S3 Glacier 检索数据时，您可以选择 3 个还原优先级；从 Amazon S3 Glacier Deep Archive 检索数据时，您可以选择 2 个还原优先级。  S3 Glacier Deep Archive 的成本低于 S3 Glacier：
+
--
[cols="25,25,25,25"]
|===
| 存档层 3+| 恢复优先级和成本 


|  | *高的* | *标准* | *低的* 


| *S3 冰川* | 检索速度最快，成本最高 | 检索速度较慢，成本较低 | 检索速度最慢，成本最低 


| *S3 Glacier 深度存档* |  | 检索速度更快，成本更高 | 检索速度较慢，成本最低 
|===
每种方法都有不同的每 GB 检索费用和每请求费用。有关 AWS 区域 S3 Glacier 的详细定价，请访问 https://aws.amazon.com/s3/pricing/["Amazon S3 定价页面"^]。

--
恢复存档在 Amazon S3 Glacier 中的对象需要多长时间？:: 总还原时间由两部分组成：
+
--
* *检索时间*：从存档中检索备份文件并将其放置在标准存储中的时间。这有时被称为“补水”时间。检索时间根据您选择的恢复优先级而不同。
+
[cols="25,20,20,20"]
|===
| 存档层 3+| 恢复优先级和检索时间 


|  | *高的* | *标准* | *低的* 


| *S3 冰川* | 3-5分钟 | 3-5小时 | 5-12小时 


| *S3 Glacier 深度存档* |  | 12 小时 | 48 小时 
|===
* *恢复时间*：从标准存储中的备份文件恢复数据的时间。这次与不使用存档层时直接从标准存储进行的典型恢复操作没有什么不同。


有关 Amazon S3 Glacier 和 S3 Glacier Deep Archive 检索选项的更多信息，请参阅 https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["关于这些存储类别的 Amazon 常见问题解答"^]。

--

