---
settings:
  name: NetApp Backup and Recovery
  release_notes_autogen:
    release_notes_repo: console-local-relnotes, console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: NetApp Backup and Recovery文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: NetApp 备份和恢复中的新增功能
      url: "/whats-new.html"
    - title: ONTAP卷工作负载的已知限制
      url: "/br-reference-limitations.html"
    - title: SQL Server 工作负载的已知限制
      url: "/br-limitations.html"
    - title: VMware 工作负载的已知限制
      url: "/br-limitations-vmware.html"
    - title: Hyper-V 工作负载的已知限制
      url: "/br-limitations-hyperv.html"
    - title: KVM 工作负载的已知限制
      url: "/br-limitations-kvm.html"
    - title: Oracle 数据库工作负载的已知限制
      url: "/br-limitations-oracle.html"
  - title: 开始使用
    entries:
    - title: 了解NetApp Backup and Recovery
      url: "/concept-backup-to-cloud.html"
    - title: NetApp Backup and Recovery 要求
      url: "/concept-start-prereq.html"
    - title: 设置许可
      url: "/br-start-licensing.html"
    - title: 设置安全证书
      url: "/task-setup-ca-certificates.html"
    - title: 在使用NetApp Backup and Recovery之前设置备份目标
      url: "/br-start-setup.html"
    - title: 发现异地备份目标
      url: "/br-start-discover-backup-targets.html"
    - title: 切换到不同的NetApp Backup and Recovery工作负载
      url: "/br-start-switch-ui.html"
    - title: 配置NetApp Backup and Recovery设置
      url: "/br-start-configure.html"
    - title: 设置基于角色的访问控制
      url: "/br-rbac-setup.html"
  - title: 使用NetApp Backup and Recovery
    entries:
    - title: 登录NetApp Backup and Recovery
      url: "/br-start-login.html"
    - title: 在NetApp Backup and Recovery仪表板上查看保护健康状况
      url: "/br-use-dashboard.html"
    - title: 保护ONTAP卷工作负载
      entries:
      - title: 了解适用于 ONTAP 卷的 NetApp Backup and Recovery
        url: "/prev-ontap-protect-overview.html"
      - title: 启用 NetApp Backup and Recovery 以保护卷
        url: "/br-start-enable.html"
      - title: 提高 NetApp Backup and Recovery 本地部署中的搜索和还原性能
        url: "/prev-ontap-protect-migrate-pvc.html"
      - title: NetApp Backup and Recovery 中的保护旅程规划选项
        url: "/prev-ontap-protect-journey.html"
      - title: 无需激活即可发现 ONTAP 系统和卷
        url: "/prev-ontap-discover-no-activate.html"
      - title: 管理 ONTAP 卷的备份策略
        url: "/prev-ontap-policy-manage.html"
      - title: ONTAP 卷备份到对象策略选项
        url: "/prev-ontap-policy-object-options.html"
      - title: 管理备份到对象存储选项
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: 将Cloud Volumes ONTAP数据备份到 Amazon S3
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: 将 Cloud Volumes ONTAP 数据备份到 Azure Blob 存储
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: 将 Cloud Volumes ONTAP 数据备份到 Google Cloud Storage
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: 将本地ONTAP数据备份到 Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: 将本地 ONTAP 数据备份到 Azure Blob 存储
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: 将本地 ONTAP 数据备份到 Google Cloud Storage
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: 将本地ONTAP数据备份到ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: 将本地 ONTAP 数据备份到兼容 S3 的存储
        url: "/prev-ontap-backup-onprem-s3-compatible.html"
      - title: 将本地ONTAP数据备份到StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: 使用 SnapMirror 将 ONTAP 卷迁移到云重新同步
        url: "/prev-ontap-migrate-resync.html"
      - title: 管理 ONTAP 系统的备份
        url: "/prev-ontap-backup-manage.html"
      - title: 从ONTAP备份还原
        entries:
        - title: ONTAP 数据还原选项
          url: "/prev-ontap-restore.html"
        - title: 使用搜索和还原功能还原 ONTAP 数据
          url: "/prev-ontap-restore-search.html"
        - title: 使用浏览和还原功能还原 ONTAP 数据
          url: "/prev-ontap-restore-browse.html"
    - title: 保护 Microsoft SQL Server 工作负载
      entries:
      - title: Microsoft SQL Server 在 NetApp Backup and Recovery 中的保护工作流
        url: "/br-use-mssql-protect-overview.html"
      - title: SnapCenter 导入 NetApp Backup and Recovery 的先决条件
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: 发现 Microsoft SQL Server 工作负载
        url: "/br-start-discover.html"
      - title: 创建和管理 Microsoft SQL Server 备份策略
        url: "/br-use-policies-mssql-create.html"
      - title: 备份 Microsoft SQL Server 工作负载
        url: "/br-use-mssql-backup.html"
      - title: 恢复 Microsoft SQL Server 工作负载
        url: "/br-use-mssql-restore.html"
      - title: 克隆 Microsoft SQL Server 工作负载
        url: "/br-use-mssql-clone.html"
      - title: 管理 Microsoft SQL Server 库存
        url: "/br-use-manage-inventory.html"
      - title: 管理 Microsoft SQL Server 快照
        url: "/br-use-manage-snapshots.html"
      - title: 创建 Microsoft SQL Server 报告
        url: "/br-use-reports.html"
    - title: 保护 VMware 工作负载
      entries:
      - title: VMware 保护工作流
        url: "/br-use-vmware-protect-overview.html"
      - title: 发现 VMware 工作负载
        url: "/br-use-vmware-discovery.html"
      - title: 管理 VMware 保护组
        url: "/br-use-vmware-protection-groups.html"
      - title: 管理 VMware 备份策略
        url: "/br-use-policies-vmware-create.html"
      - title: 备份 VMware 工作负载
        url: "/br-use-vmware-backup.html"
      - title: 克隆 VMware 工作负载
        url: "/br-use-vmware-clone.html"
      - title: 恢复 VMware 工作负载
        entries:
        - title: 恢复 VMware 工作负载
          url: "/br-use-vmware-restore.html"
        - title: 从备份还原 VMware 虚拟磁盘
          url: "/br-use-vmware-restore-vmdks-from-backups.html"
        - title: 还原 VMware 文件和文件夹
          entries:
          - title: VMware 来宾文件还原要求
            url: "/br-use-vmware-restore-guest-files-and-folders-overview.html"
          - title: 还原 VMware 来宾文件和文件夹
            url: "/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html"
          - title: 文件和文件夹恢复故障排除
            url: "/br-use-vmware-guest-file-restore-scenarios-you-might-encounter.html"
    - title: 保护KVM工作负载
      entries:
      - title: 保护 KVM 工作负载概述
        url: "/br-use-kvm-protect-overview.html"
      - title: 发现 KVM 工作负载
        url: "/br-start-discover-kvm.html"
      - title: 为 KVM 工作负载创建和管理保护组
        url: "/br-use-kvm-protection-groups.html"
      - title: 创建和管理 KVM 工作负载备份策略
        url: "/br-use-policies-kvm-create.html"
      - title: 备份 KVM 工作负载
        url: "/br-use-kvm-backup.html"
      - title: 恢复 KVM 工作负载
        url: "/br-use-kvm-restore.html"
    - title: 保护 Hyper-V 工作负载
      entries:
      - title: 保护 Hyper-V 工作负载概述
        url: "/br-use-hyperv-protect-overview.html"
      - title: 发现 Hyper-V 工作负载
        url: "/br-start-discover-hyperv.html"
      - title: 为 Hyper-V 工作负载创建和管理保护组
        url: "/br-use-hyperv-protection-groups.html"
      - title: 创建和管理 Hyper-V 工作负载备份策略
        url: "/br-use-policies-hyper-v-create.html"
      - title: 备份 Hyper-V 工作负载
        url: "/br-use-hyperv-backup.html"
      - title: 恢复 Hyper-V 工作负载
        entries:
        - title: 恢复 Hyper-V 工作负载
          url: "/br-use-hyperv-restore.html"
        - title: 还原 Hyper-V 文件和文件夹
          url: "/br-use-hyper-v-restore-guest-files-and-folders.html"
    - title: 保护 Oracle Database 工作负载（预览）
      entries:
      - title: 保护 Oracle 数据库工作负载概述
        url: "/br-use-oracle-protect-overview.html"
      - title: 发现 Oracle Database 工作负载
        url: "/br-start-discover-oracle.html"
      - title: 配置 Oracle 数据库
        url: "/br-start-configure-oracle-database.html"
      - title: 为 Oracle Database 工作负载创建和管理保护组
        url: "/br-use-oracle-protection-groups.html"
      - title: 创建和管理 Oracle Database 工作负载备份策略
        url: "/br-use-policies-oracle-create.html"
      - title: 备份 Oracle Database 工作负载
        url: "/br-use-oracle-backup.html"
      - title: 克隆 Oracle 数据库工作负载
        url: "/br-use-oracle-clone.html"
      - title: 还原 Oracle Database 工作负载
        url: "/br-use-oracle-restore.html"
      - title: 装载、卸载和编目恢复点
        url: "/br-use-oracle-mount-unmount.html"
    - title: 保护 Kubernetes 工作负载
      entries:
      - title: 保护 Kubernetes 工作负载概述
        url: "/br-use-kubernetes-protect-overview.html"
      - title: 发现 Kubernetes 工作负载
        url: "/br-start-discover-kubernetes.html"
      - title: 添加和保护 Kubernetes 应用程序
        entries:
        - title: 添加和保护 Kubernetes 应用程序
          url: "/br-use-protect-kubernetes-applications.html"
        - title: 创建和管理 Kubernetes 工作负载备份策略
          url: "/br-use-policies-kubernetes-create.html"
        - title: 立即使用 Web UI 备份 Kubernetes 应用程序
          url: "/br-use-back-up-now-kubernetes-applications-web-ui.html"
        - title: 现在使用自定义资源备份 Kubernetes 应用程序
          url: "/br-use-back-up-now-kubernetes-applications-cr.html"
      - title: 恢复 Kubernetes 应用程序
        entries:
        - title: 使用 Web UI 还原 Kubernetes 应用程序
          url: "/br-use-restore-kubernetes-applications.html"
        - title: 使用自定义资源恢复 Kubernetes 应用程序
          url: "/br-use-restore-kubernetes-applications-cr.html"
        - title: 使用高级自定义资源还原设置
          url: "/br-use-kubernetes-advanced-restore-settings.html"
        - title: 在还原操作期间使用自定义资源修改资源
          url: "/br-use-modify-resources-kubernetes-cr.html"
      - title: 管理 Kubernetes 集群
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: 管理 Kubernetes 应用程序
        url: "/br-use-manage-kubernetes-applications.html"
      - title: 管理 Kubernetes 工作负载的执行钩子模板
        url: "/br-use-manage-execution-hook-templates.html"
      - title: 创建和管理保护报告
        url: "/br-use-kubernetes-reports.html"
    - title: 监控作业
      url: "/br-use-monitor-tasks.html"
    - title: 重新启动NetApp Backup and Recovery
      url: "/reference-restart-backup.html"
    - title: 启用预览和隐藏功能
      url: "/enable-preview-features.html"
  - title: 使用NetApp Backup and RecoveryREST API 实现自动化
    url: "/br-api-backup-restore.html"
  - title: 参考
    entries:
    - title: 审核 NetApp Backup and Recovery 操作
      url: "/reference-audit-actions.html"
    - title: SnapCenter中的策略与NetApp Backup and Recovery中的策略比较
      url: "/reference-policy-differences-snapcenter.html"
    - title: NetApp Backup and Recovery IAM 角色
      url: "/reference-roles.html"
    - title: 在暗站中恢复NetApp Backup and Recovery配置数据
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: NetApp Backup and Recovery支持的 AWS 存档存储层
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: 通过 NetApp Backup and Recovery 支持的 Azure 存档存储层
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: 通过 NetApp Backup and Recovery 支持的 Google Cloud 存档存储层
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
