= 高性能索引
:allow-uri-read: 




=== 高性能索引

NetApp Backup and Recovery 引入了更新的索引功能，使源系统上的数据索引更加高效。新的索引功能包括 UI 的更新、数据恢复搜索和恢复方法性能的改进、全局搜索功能的升级以及更好的可扩展性。

以下是改进的具体内容：

* *文件夹合并*：更新后的版本使用包含特定标识符的名称将文件夹分组在一起，使索引过程更加顺畅。
* *Parquet 文件压缩*：更新后的版本减少了用于索引每个卷的文件数量，简化了流程并消除了对额外数据库的需求。
* *通过更多会话进行扩展*：新版本增加了更多会话来处理索引任务，从而加快了进程。
* *支持多个索引容器*：新版本使用多个容器来更好地管理和分配索引任务。
* *分割索引工作流程*：新版本将索引过程分为两部分，提高了效率。
* *改进的并发性*：新版本可以同时删除或移动目录，从而加快索引过程。


.谁能从此功能中受益？
所有新客户均可使用新的索引功能。

.如何启用索引？
在使用搜索和恢复方法恢复数据之前，您需要在计划恢复卷或文件的每个源系统上启用“索引”。这使得索引目录可以跟踪每个卷和每个备份文件，从而使您的搜索快速而高效。

执行搜索和还原时，通过选择“启用索引”选项在源工作环境上启用索引。

有关详细信息，请参阅文档 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["如何使用“搜索和还原”还原ONTAP数据"]。

.支持规模
新的索引功能支持以下内容：

* 3分钟内即可实现全球搜索效率
* 最多 50 亿个文件
* 每个集群最多 5000 个卷
* 每个卷最多 10 万个快照
* 基线索引的最长时间少于 7 天。实际时间将根据您的环境而有所不同。




=== 全局搜索性能改进

此版本还包括对全局搜索性能的增强。您现在将看到进度指示器和更详细的搜索结果，包括文件数量和搜索所花费的时间。专用的搜索和索引容器可确保全局搜索在五分钟内完成。

请注意与全局搜索相关的以下注意事项：

* 新索引不会在标记为每小时的快照上执行。
* 新的索引功能仅适用于 FlexVols 上的快照，而不适用于 FlexGroups 上的快照。

