= 索引目录支持更新
:allow-uri-read: 




=== 索引目录支持更新

2025 年 2 月，我们推出了更新的索引功能（索引目录 v2），您可以在“搜索和还原”数据恢复方法中使用该功能。以前的版本显著提高了本地环境中的数据索引性能。在此版本中，索引目录现在可用于 Amazon Web Services、Microsoft Azure 和 Google Cloud Platform (GCP) 环境。

如果您是新客户，则所有新环境均默认启用 Indexed Catalog v2。如果您是现有客户，您可以重新索引您的环境以利用 Indexed Catalog v2。

.如何启用索引？
在使用搜索和还原方法还原数据之前，您需要在计划还原卷或文件的每个源工作环境上启用“索引”。执行搜索和恢复时，选择“启用索引”选项。

索引目录可以跟踪每个卷和备份文件，使您的搜索快速而高效。

更多信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["启用搜索和还原索引"]。



=== Azure 专用链接终结点和服务终结点

通常， NetApp Backup and Recovery会与云提供商建立一个私有端点来处理保护任务。此版本引入了一个可选设置，可让您启用或禁用NetApp Backup and Recovery自动创建私有端点。如果您想要更好地控制私有端点创建过程，这可能对您有用。

您可以在启用保护或开始恢复过程时启用或禁用此选项。

如果禁用此设置，则必须手动创建私有端点以使NetApp Backup and Recovery正常运行。如果没有适当的连接，您可能无法成功执行备份和恢复任务。



=== ONTAP S3 上支持SnapMirror到云重新同步

以前的版本引入了对SnapMirror到 Cloud Resync（SM-C Resync）的支持。该功能简化了NetApp环境中卷迁移期间的数据保护。此版本增加了对ONTAP S3 上的 SM-C Resync 以及其他与 S3 兼容的提供商（如 Wasabi 和 MinIO）的支持。



=== 为StorageGRID带来您自己的存储桶

当您在对象存储中为工作环境创建备份文件时，默认情况下， NetApp Backup and Recovery会为您配置的对象存储帐户中的备份文件创建容器（存储桶或存储帐户）。以前，您可以覆盖此功能并为 Amazon S3、Azure Blob Storage 和 Google Cloud Storage 指定您自己的容器。通过此版本，您现在可以携带自己的StorageGRID对象存储容器。

看 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-journey.html["创建您自己的对象存储容器"]。
