= UI改进
:allow-uri-read: 




=== UI改进

此版本通过简化界面来增强您的体验：

* 从卷表中删除聚合列，以及从 V2 仪表板中的卷表中删除快照策略、备份策略和复制策略列，可实现更简化的布局。
* 从下拉列表中排除未激活的工作环境可以使界面更简洁、导航更高效、加载更快。
* 虽然标签列的排序功能被禁用，但您仍然可以查看标签，确保重要信息仍然易于访问。
* 删除保护图标上的标签有助于使外观更清晰并减少加载时间。
* 在工作环境激活过程中，对话框会显示加载图标以提供反馈，直到发现过程完成，从而增强系统操作的透明度和信心。




=== 增强型音量仪表板（预览版）

音量仪表板现在可在 10 秒内加载，提供更快、更高效的界面。此预览版可供部分客户使用，让他们可以提前了解这些改进。



=== 支持第三方 Wasabi 对象存储（预览版）

NetApp Backup and Recovery现在将其支持扩展到第三方对象存储，主要关注 Wasabi。此新的预览功能使您可以利用任何与 S3 兼容的对象存储来满足您的备份和恢复需求。



==== 开始使用 Wasabi

要开始使用第三方存储作为对象存储，您必须在控制台代理中启用一个标志。然后，您可以输入第三方对象存储的连接详细信息并将其集成到备份和恢复工作流程中。

.步骤
. 通过 SSH 进入您的连接器。
. 进入NetApp Backup and Recovery cbs 服务器容器：
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 打开 `default.json`文件里面 `config`通过 VIM 或任何其他编辑器文件夹：
+
[listing]
----
vi default.json
----
. 调整 `allow-s3-compatible`：假 `allow-s3-compatible`： 真的。
. 保存更改。
. 从容器中退出。
. 重新启动NetApp Backup and Recovery cbs 服务器容器。


.结果
容器再次打开后，打开NetApp Backup and RecoveryUI。当您启动备份或编辑备份策略时，您将看到新的提供商“S3 Compatible”与 AWS、Microsoft Azure、Google Cloud、 StorageGRID和ONTAP S3 等其他备份提供商一起列出。



==== 预览模式限制

虽然此功能处于预览状态，但请考虑以下限制：

* 不支持自带水桶 (BYOB)。
* 不支持在策略中启用 DataLock。
* 不支持在策略中启用存档模式。
* 仅支持本地ONTAP环境。
* 不支持 MetroCluster。
* 不支持启用存储桶级加密的选项。


在此预览期间，我们鼓励您在推出完整功能之前探索此新功能并提供有关与第三方对象存储集成的反馈。
