= 常规 NetApp Backup and Recovery 增强功能
:allow-uri-read: 




[[general-netapp-backup-and-recovery-enhancements]]
=== 常规 NetApp Backup and Recovery 增强功能

* *支持 NetApp Console 本地部署*：此版本的 NetApp Backup and Recovery 支持处于预览状态的 NetApp Console 本地部署。
* *90 天的作业保留*：Backup and Recovery 现在会在 Job Monitor 中保留作业信息 90 天。




[[vmware-workloads-enhancements]]
=== VMware 工作负载增强功能

在此版本中，VMware 工作负载引入了以下增强功能：

* *还原到备用位置支持（适用于 SAN VM）*：现在，您可以将基于 SAN 的 VM 备份还原到备用位置。
* *Multiple backup delete support*：您现在可以一次删除多个备份。


有关保护 VMware 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["保护 VMware 工作负载概述"]。



[[oracle-database-workloads-enhancements]]
=== Oracle Database 工作负载增强

在此版本中，Oracle 数据库工作负载引入了以下增强功能：

* *可插拔数据库(PDB)还原和克隆*：Backup and Recovery for NetApp Console 服务现在支持还原和克隆可插拔数据库。


要了解有关保护 Oracle Database 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["保护 Oracle 数据库工作负载概述"]。



[[kubernetes-workloads-enhancements]]
=== Kubernetes 工作负载增强功能

在此版本中，Kubernetes 工作负载引入了以下增强功能：

* *预览对气隙资源的支持*：如果在 NetApp Console 本地部署中运行 NetApp Backup and Recovery，您可以发现、保护和还原气隙 Kubernetes 资源。此功能在此版本中处于预览状态。


有关保护 Kubernetes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["保护 Kubernetes 工作负载概述"]。



[[ontap-volumes-workloads-enhancements]]
=== ONTAP Volumes 工作负载增强

在此版本中，ONTAP Volumes 工作负载引入了以下增强功能：

* *将还原作业优先于备份*：现在，在还原虚拟机或文件时，您可以将还原作业优先于备份作业。
* *在不激活 Backup and Recovery 的情况下发现 ONTAP 系统和卷*：您现在可以在不激活 Backup and Recovery 的情况下发现系统和卷。


要了解有关保护 ONTAP Volumes 工作负载的详细信息，请参阅 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["保护 ONTAP 卷工作负载概述"]。
